### ISSUE TITLE
resultOf is missing

### ISSUE THREAD

**Issue by fmoda3** [ligee/kotlin-jupyter#10]
Commit df1e7e3a66e74fd7118e2a8764f276f2caf6f20d deleted resultOf.

The sample is now broken.

`error: unresolved reference: resultOf
resultOf(convolutionExample().toSvg(1000.0, 500.0))`

**Comment by hanslovsky** [comment]
Does that mean that inline image support does not work currently? I c&p'ed the contents of `results.kt` into a notebook, like this:
```kotlin
class Result(mimeData: Map<String, Any>) : Map<String, Any> by mimeData
fun resultOf(vararg mimeToData: Pair<String, Any>): Result = Result(mapOf(*mimeToData))
resultOf(convolutionExample().toSvg(1000.0, 500.0))
```
I only see:
```
Line18$Result@61217336
```

**Comment by apatrida** [comment]
This was fixed today on MASTER
