### ISSUE TITLE
Package level functions can not be used

### ISSUE THREAD

**Issue by holgerbrandl** [ligee/kotlin-jupyter#13]
Example (from a a file src/main/kotlin/de/mpicbg/scicomp/kip/Util.kt and pulled into the jupyter repl using `@DependsOnMaven`):
```
fun hello() = println("hello from in here")
```
It does not seem possible to do wildcard import for it, not to call it directly: 
![image](https://user-images.githubusercontent.com/200952/32944228-1803d5e8-cb8f-11e7-9fee-25c30401158a.png)

**Comment by apatrida** [comment]
This is likely an outdated problem that is fixed in later Kotlin resolvers.  And update to current dependencies might fix this, so let's recheck after that.

**Comment by holgerbrandl** [comment]
Sounds great to me. Looking forward to the updated release!

**Comment by holgerbrandl** [comment]
I've tested against current master, with 
```kotlin
@file:DependsOnMaven("de.mpicbg.scicomp:krangl:0.7")

import krangl.*

irisData.glimpse()
```
and in deed the bug is fixed now. Thanks!
