### ISSUE TITLE
After a a println command "Ok" is printed instead of the actual string to be printed.

### ISSUE THREAD

**Issue by oroszgy** [ligee/kotlin-jupyter#3]
Having the row 

``` Kotlin
println("hello")
```

`Ok` is printed and not `"Hello"`

**Comment by happy15** [comment]
+1

**Comment by apatrida** [comment]
The result of `println(...)` is of type `Unit` and therefore on that type of response the `Ok` is printed as a result of the call.  If you want to print "Hello" you can just put that string.  or for example of a variable:

```
>>> val x = 10;
Ok

>>> x
10
```
Do other interpreters copy the output of stdout to the response?

**Comment by apatrida** [comment]
So for something that returns `Unit` type, we can print `<no return value>` instead to make it clearer, ... I'm asking about capturing standard-out from the reply eval engine now, if so we can fix capturing stdout output as well.

**Comment by oroszgy** [comment]
Hi, thanks for the reply. Other interpreters tend to capture the stdout, so I think that would be a useful feature here as well.

**Comment by apatrida** [comment]
I did a quick hack to check capturing stdout, and I was able to do so.   But, it isn't pretty.  Need to see if the evaluator can have it set directly instead of changing the global `System.out` printstream.

**Comment by apatrida** [comment]
Ok, basically just forking the `System.out` both to the console and to the publishing of output back to Jupyter.  Anything running that does output will accidentally send data back to Jupyter, so inadvertant output could come back.  And not sure if Jupyter limits how much it accepts so that it doesn't end up with megs of data coming back on some accident.  I think a configuration parameter would be good for turning the forking of stdout on, and also the limit per eval call that could be sent back as a fail-safe.

**Comment by apatrida** [comment]
I have some refactoring to do, then will commit fixes for this and the repeat crash later...

**Comment by apatrida** [comment]
When piping stdout back, it shows up in jupyter-console, but in jupyter-notebook it does not.  So therefore stdout has to be mapped back as the return value.  I'll take a look to see what other kernels do in the same situation (if they pass back something with a mime type, or just as a text value, ...)

**Comment by apatrida** [comment]
If you want, please try my fork at https://github.com/apatrida/kotlin-jupyter

and I'll do a PR from there based on feedback.

**Comment by apatrida** [comment]
![screen shot 2016-12-29 at 11 06 44 am](https://cloud.githubusercontent.com/assets/182340/21545568/78e2c008-cdb7-11e6-8e43-1b34c7d23ba5.png)

**Comment by apatrida** [comment]
What does not work is if you do output AND return a value, the value will win.

**Comment by apatrida** [comment]
@ligee please close, fixed in previous PR
